role: "[Role Name]"
description: >
  [A comprehensive description of the role's purpose and main responsibilities]

responsibilities:
  - [Key task or duty 1]
  - [Key task or duty 2]
  - [Key task or duty 3]
  - [Add more as needed]

expertise:
  - [Technical skill or knowledge 1]
  - [Technical skill or knowledge 2]
  - [Technical skill or knowledge 3]
  - [Add more as needed]

tools_and_technologies:
  - "Essential: [Essential tool or technology 1]"
  - "Essential: [Essential tool or technology 2]"
  - "Recommended: [Recommended tool or technology 1]"
  - "Recommended: [Recommended tool or technology 2]"

characteristics:
  - [Personal quality or soft skill 1]
  - [Personal quality or soft skill 2]
  - [Personal quality or soft skill 3]
  - [Add more as needed]

interaction_with:
  - "[Role 1] (receives: what they receive; provides: what they provide)"
  - "[Role 2] (collaborates: nature of collaboration)"
  - "[Role 3] (advises: nature of advisory relationship)"
  - "[Add more as needed]"

decision_authority:
  - [Area of decision-making authority 1]
  - [Area of decision-making authority 2]
  - [Area of decision-making authority 3]
  - [Add more as needed]

scalability:
  - "Small team: [How the role functions in a small team]"
  - "Large team: [How the role scales or specializes in a large team]"

agile_mapping:
  - "Scrum role: [Corresponding Scrum role]"
  - "Sprint Planning: [Role's responsibilities in Sprint Planning]"
  - "Daily Scrum: [Role's responsibilities in Daily Scrum]"
  - "Sprint Review: [Role's responsibilities in Sprint Review]"
  - "Sprint Retrospective: [Role's responsibilities in Sprint Retrospective]"
  - "Backlog Refinement: [Role's responsibilities in Backlog Refinement]"

knowledge_sharing:
  - [Knowledge sharing activity or responsibility 1]
  - [Knowledge sharing activity or responsibility 2]
  - [Knowledge sharing activity or responsibility 3]
  - [Add more as needed]

career_path:
  - "Next steps: [Potential next career steps]"
  - "Skills to develop: [Skills to develop for career advancement]"

remote_work_considerations:
  - [Remote work consideration or best practice 1]
  - [Remote work consideration or best practice 2]
  - [Remote work consideration or best practice 3]
  - [Add more as needed]

success_criteria:
  - [Success criterion 1]
  - [Success criterion 2]
  - [Success criterion 3]
  - [Add more as needed]

key_performance_indicators:
  - "[KPI 1 name]: [KPI 1 description or measurement]"
  - "[KPI 2 name]: [KPI 2 description or measurement]"
  - "[KPI 3 name]: [KPI 3 description or measurement]"
  - "[Add more as needed]" 